### PR TITLE
PATMOS-x monthly means and time series

### PR DESCRIPTION
**Pull request by adriaat**
Scripts to compute PATMOS-x (hourly) monthly means from raw data.
Notebook showing monthly mean trends and full-CDR averaged values.

When computing the averages, I use weights that depend on the number of values available for the given pixel, and computing the overall average, the weights are combined with the cosine of latitude.

### CODE REVIEW

**Comment by adriaat** [comment]
#12 Needs to be closed before approving and merging this.

**Comment by adriaat** [comment]
I've finished the time series, but I'm running an analysis to assert there's no difference between `tiwp_mixed` and `tiwp`.

**Comment by adriaat** [comment]
The 'results' netCDF is `/scratch/ccic_record/data/PATMOS-x/means/PATMOS-x_timeseries198108-201912_notebook_results.nc`
Only the period 1981/08-2019/12 was used as this period contains version 'final' files. From 2020 onwards I only found 'preliminary'.

**Review by simonpf — COMMENTED** [review]
Very nice work, as usual.

Notebook runs as expected.

Just one comment: It seems that the number of counts used for calculating the TIWP exhibits much more structure than the actual TIWP mean. That suggests to me that the calculated mean is conditional, i.e., only calculated over pixels with non-zero TIWP. However, for the comparison to the other datasets, we need absolute mean. Could you double check that this is correct?

**Comment by adriaat** [comment]
Your assumption is correct.
In the notebook:
> `tiwp` is obtained by considering the cloud water path of those pixels which are indicated to have an ice cloud phase.

I guess I calculated the conditional mean because of the binary (categorical) nature of PATMOS-x data concerning TIWP: the vertical column is reduced to either `clear`, `water`, `supercooled_water`, `mixed`, `ice`, `unknown`.

I am processing a new series with the absolute mean, assuming that when the cloud phase is not `ice` TIWP is 0.

**Comment by adriaat** [comment]
It wasn't that straightforward.

PATMOS-x data had to be re-downloaded. Addressed with PR #18.

Now the PATMOS-x 'custom raw' files contain the variable `cld_iwp_dcomp` which can be used directly to compute the means.

Also extended to cover more time: using all PATMOS-x v6.00 files up to this year excluding those that are version `preliminary`.

**Comment by adriaat** [comment]
Since the review isn't complete, I now added the spatial maps suggested in the last meeting

**Review by simonpf — APPROVED** [review]
Great work! Thank you!

**Pull request merged**
